name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor app
        run: |
          dotnet publish OnixLabs.Web/OnixLabs.Web.csproj \
            -c Release \
            -o release \
            --nologo

      - name: Copy CNAME file
        run: |
          cp CNAME release/wwwroot/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
